[package]
name = "surfboard"
version = "1.0.0"
edition = "2021"


[dependencies]
env_logger = "0.11.6"
log = "0.4.22"
iced = "0.13.1"
iced_layershell = "0.13.2"
iced_aw = "0.11.0"
#iced_fonts = "0.1.1"


[features]
default = [
 #   "eframe/wayland",
 #   "egui_extras/image",
    ]


# bleeding edge version of egui and eframe:
[patch.crates-io]
#egui = { git = "https://github.com/emilk/egui", branch = "master" }
#eframe = { git = "https://github.com/emilk/egui", branch = "master" }
